#### Introduction 

In [1]:
import numpy as np

In [2]:
numpy_array=np.array([1,2,5,6,7,8])

In [3]:
print(numpy_array)

[1 2 5 6 7 8]


In [4]:
list=[1,2,3,4,5]

In [5]:
print(list)

[1, 2, 3, 4, 5]


##### Above you see the difference between list and array. list is stored with  , where array is without , it uses less space

##### 1D Array is list of number store in a row

In [6]:
numpy_array=np.array([1,2,5,6,7,8])
print(numpy_array)

[1 2 5 6 7 8]


##### 2d Array is collection of rows and columns

In [7]:
arr_2d=np.array([[1,2,3],
                 [3,4,5],
                 [4,5,6]])

print(arr_2d)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


##### Multi dimensional Array 
##### Matrix

In [8]:
matrix=np.array([[8,4,5],
                 [2,2,3]])
print(matrix)

[[8 4 5]
 [2 2 3]]


##### With default values (0) np.zeros(shape) then three value will be zero

In [9]:
default_array=np.zeros(3)
print(default_array)

[0. 0. 0.]


##### Same for one if you want default value one np.ones(shape)

In [10]:
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


##### If you want other values like 2,3 etc Then we use np.full(shape,value)

In [12]:
filled_values=np.full((2,4),5)
print(filled_values)

[[5 5 5 5]
 [5 5 5 5]]


##### Creating a sequence of numbers in numpy
##### np.arange()
##### np.arange(start,stop,step)

In [14]:
arr=np.arange(1,19,3)
print(arr)

[ 1  4  7 10 13 16]


##### Creating a identity matrix (all diagonal element is one)
##### np.eye(size)

In [16]:
identity_mat=np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
