## Insert
#### np.insert(array,index,value,axis=None) 
#### array=original array
#### index= jis index
#### value= konsi value
#### axis=none if 1d array
#### axis=0,row wise 1 cloumn_wise

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8])
print(np.insert(arr,8,9)) # by default axis is 0 for 1d

[1 2 3 4 5 6 7 8 9]


## insert_in_2d_array

In [4]:
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])
array=np.insert(arr,0,[2,4],axis=0) # add new element row inside data
print(array)


[[2 4]
 [1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])
array=np.insert(arr,0,[2,4,7,8],axis=1) # add new element in 0th column inside data
print(array)


[[2 1 2]
 [4 3 4]
 [7 5 6]
 [8 7 8]]


## Append
##### np.append(arr,[elments]) add elments at the and of Array

In [6]:
arr=np.array([1,2,3,4,5,6,7,8])
print(np.append(arr,[9,10,11]))

[ 1  2  3  4  5  6  7  8  9 10 11]


## Concatenate

##### np.concatenate((array1,array2),axis=0) for 1d array axis is by default



In [15]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.concatenate((arr1,arr2)))



[1 2 3 4 5 6 7 8]


## Remove Elemet from array


#### np.delete(array,index,axis=none)

In [8]:
arr=np.array([1,2,3,4])
print(arr)
arr=np.delete(arr,1)
print(arr) # 2 element is deleted from array

[1 2 3 4]
[1 3 4]


#### Delete_2d

In [ ]:
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])
array=np.delete(arr,1,axis=1) # remove elments from 1st index column means 2,4,6,8
print(array)

[[1]
 [3]
 [5]
 [7]]


In [ ]:
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])
array=np.delete(arr,1,axis=0) # remove 1st index row mean[3,4]
print(array)

[[1 2]
 [5 6]
 [7 8]]


### Stacking 
#### hstack np.hstack((arr1,arr2)) use double bracket it combine arrays horizontally
#### vstack np.vstack((arr1,arr2)) use double bracket it combine arrays vertically like in 2d

In [17]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))




[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Splitting
#### np.split() equally split the array  (np.hsplit(for horizontal split), np.vsplit(for vertical split))

In [ ]:
arr=np.array([4,6,8,9,10,22,33,4])
print(np.split(arr,2)) # Split the array in two parts it works for all dimensional arrays
print(np.hsplit(arr,2)) # Split the array in two parts

## example 


[array([4, 6, 8, 9]), array([10, 22, 33,  4])]
[array([4, 6, 8, 9]), array([10, 22, 33,  4])]


In [ ]:
arr=np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])

print(np.vsplit(arr,2)) # it split array and split into 2 sub array by row 
print(np.split(arr, 2, axis=1)) # it split array  in to two subarray (with thier own subarrays) xby columns
print(np.hsplit(arr, 2)) 

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
